#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
~/.config/polybar/launch.sh --material

bspc config border_width        2
bspc config window_gap          15
bspc config normal_border_color '#cf3c3c'
bspc config focused_border_color '#8271d9'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xterm -hold -e "bash -c 'neofetch; exec bash'"
